name: lint

on:
  push:
    branches: [ master ]
    paths:
      - '**.py'
  pull_request:
    branches: [ master ]
    paths:
      - '**.py'

jobs:
  lint:
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependency
        run: pip install black flake8 mypy
      - name: Run black
        run: black neosca/ tests/ --line-length 97 --preview
      - name: Run flake8
        run: flake8 neosca/ tests/ --count --max-line-length=97 --statistics --ignore=E203,E501,W503
      - name: Run mypy 
        run: mypy --check-untyped-defs neosca/
