name: lint, test, and report coverage

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  setup:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Run black
      run: black --line-length 90 --preview neosca/ tests/ 
    - name: Run mypy 
      run: mypy --check-untyped-defs neosca/
    - name: Build dist and test with unittest
      run: |
        python setup.py sdist bdist_wheel
        pip install dist/*.whl
        python -m unittest
    - name: Generate coverage report
      run: |
        coverage run --source neosca --parallel-mode -m unittest
        coverage combine
        coverage xml -i
    - name: Upload report to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
