# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies on macOS and Linux
      if: matrix.os != 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        export SHELL=bash
        python -m neosca --check-depends --yes
      shell: bash
    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        if (Test-Path -Path '.\requirements-dev.txt' -PathType Leaf) {pip install -r requirements-dev.txt}
        python -m neosca --check-depends --yes
      shell: pwsh
    - name: Build dist and test with unittest on macOS and Linux
      if: matrix.os != 'windows-latest'
      run: |
        python setup.py sdist bdist_wheel
        pip install dist/*.whl
        python -m unittest
      shell: bash
    - name: Build dist and test with unittest on Windows
      if: matrix.os == 'windows-latest'
      run: |
        python setup.py sdist bdist_wheel
        pip install (Get-ChildItem dist/*.whl)
        python -m unittest
      shell: pwsh
    - name: Generate coverage report
      run: |
        coverage run --source neosca --parallel-mode -m unittest
        coverage combine
        coverage xml -i
    - name: Upload report to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
